on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential git
        sudo apt install -y openjdk-11-jdk
        sudo apt install -y libffi-dev libssl-dev zlib1g-dev
        sudo apt install -y autoconf automake libtool pkg-config
        sudo apt install -y cmake
        sudo apt install -y libgl1 libglib2.0-0

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        pip install Cython==0.29.30
        pip install kivy buildozer python-for-android
        pip install opencv-python-headless numpy

    - name: Initialize buildozer
      run: |
        buildozer init

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: polar-align-apk
        path: bin/*.apk
        if-no-files-found: error

    - name: Upload build logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: build-logs
        path: |
          ~/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/*/*/_gradle.log
          ~/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/*.log

